remote_theme: ankitsultana/researcher@gem

title: Adrian Millea
url: "https://m3t4n01a.github.io"
baseurl: "/"

markdown: kramdown

# Google Analytics
google_analytics: UA-16290038-2

footer: yes
footer_url: "https://github.com/jekyll/jekyll"
footer_text: "made with Jekyll"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about"
 - name: "Resume"
   link: "AdrianMilleaResume.pdf"
 - name: "Projects"
   link: "/projects"
 - name: "Contact"
   link: "contact"
